version: "3.7"
services:
  vite:
    image: ghcr.io/${GITHUB_ACTOR}/vite-frontend:latest
    container_name: frontend-deploy-vite
    command: "npm run start"
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
    restart: always
    networks:
      - app
  nginx:
    image: "nginx:latest"
    container_name: frontend-deploy-nginx
    restart: unless-stopped
    volumes:
      - /home/ec2-user/vite/frontend/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
    driver: bridge
